baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "luyu.rocks" # the base hostname & protocol for your site.
title: "Code and Music"


paginate: 3 #articles per page
paginate_path: /blog/page:num #makes pagination working


#contacts
git: "https://github.com/lookrain"  #Add your github url here.
facebook: "https://www.facebook.com/yu.lu.758"  #Add your twitter url here.
weibo: "http://weibo.com/u/2353357401"

#disqus comment
disqus:
    shortname: "test" #replace with your disqus comment short name

#google analytics
google:
    tracking-id: "" #paste your tracking id here
gems:
  - jekyll-sitemap

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


ftp_host: 'ftp.luyu.rocks'  
ftp_dir: '/public_html'  
ftp_passive: false

# optional
ftp_port: 21                  # default 21  
ftp_username: 'brantscube'     # default read from stdin  
ftp_password: 'XiaoYu_3514267'
